version: '3.8'

services:
  meu-apio-admin:
    container_name: meu-apoio-admin
    build:
      context: ./.docker
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '4200:4200'
    networks:
      - dev

networks:
  dev:
    external:
      name: dev
